spring:
  application:
    name: student-server
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      uri: mongodb+srv://gautamkumar:dtu123@cluster0.mc9y9.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: dev-server
server:
  port: 8091